### ISSUE TITLE
Can't post to NewGrounds and FurAffinity

### ISSUE THREAD

**Issue by imn01** [mvdicarlo/postybirb#36]
NewGrounds: Failed message says "You have to agree terms and condition", There is checkbox at the bottom while I upload in NewGrounds, I guess that is unchecked.

FurAffinity: Failed message says "You have to make 10 post" or something like this. I can post in FurAffinity without any problem but with PB it doesn't work.
![image](https://user-images.githubusercontent.com/51266990/84722691-bfc45080-afa5-11ea-9f0a-b47c461a63b3.png)

**Comment by SeinopSys** [comment]
It's listed [in the FAQ](https://www.postybirb.com/faq.html) that you need a certain number of posts to submit to FurAffinity using this app, whether you can post using the website is a different situation by the sounds of it.

**Comment by mvdicarlo** [comment]
For NewGrounds you need to post their manually once to accept the ToS.

FurAffinity is another story at the moment. In general you need about 10-11 things (it used to be 5) in your gallery before PostyBirb is able to post there since there is a Captcha that would block it until that many are in the account.

If you already have that many in your account and it still fails with that message it could be a problem of too many posts coming in too fast.
