### ISSUE TITLE
Request: Add option for image alt text to Mastodon and Twitter

### ISSUE THREAD

**Issue by nek0** [mvdicarlo/postybirb#88]
Thanks for your great work so far!

Is it possible to add the option to add image descriptions for the visually impaired as image alt texts to submissions? On Mastodon at least it is very highly appreciated to provide these when posting visual material.

**Comment by mvdicarlo** [comment]
I believe it is through their API.
This has been something in the backlog that I haven't gotten around to quite yet but I plan on adding in the future hopefully.

**Comment by digitalcircuit** [comment]
While I'm new to developing with TypeScript, Angular/React, and Electron, I'm happy to teach myself and make an honest attempt here.  I know at least one artist that has withheld posting to the fediverse due to wanting to ensure they can provide alt text.

@mvdicarlo From a high level perspective, what would be your preferred way to approach this?

I noticed development has shifted to PostyBirb+ with [a note to contact you about contributions](https://github.com/mvdicarlo/postybirb-plus#contribution-guide ).  My initial thought would be to copy the technique used for some other submission metadata that's shared across Mastodon and Twitter (perhaps `description` and/or `rating`), but you may have other goals or plans, and this might need integrated across more websites (e.g. being able to insert the alt text into the submission description on websites that don't allow setting the alt text).

I'm also open to email discussion if preferred, or filing a new issue on PostyBirb+, or whatever works best for you.  I might be slow to reply as I'm addressing unrelated stuff.

**Comment by digitalcircuit** [comment]
Good news - [support for alt text on Mastodon appears to be a part of PostyBirb v3.1.3 or newer](https://github.com/mvdicarlo/postybirb-plus/commit/11b2d994d198f292e5e0d184218ba6eb71d4e89f )!

**Comment by GracieArt** [comment]
Tumblr also has a image description field, though idk if that should go here or if a different issue should be opened for that.
